### PR TITLE
Use the built-in stage option to determine the environment

### PR DESCRIPTION
**Pull request by yooouuri**
Console.log what environment is used
Updated the README.md and the example
Added .idea folder to the .gitignore

### CODE REVIEW

**Comment by colynb** [comment]
I'm reviewing this now. Thanks!

**Review by colynb — CHANGES_REQUESTED** [review]
It looks like you've replaced `--env` with `--stage` which would break some folks existing implementation if they're still using --env. It would be better to use --stage in addition to --env. Does that make sense?

**Comment by yooouuri** [comment]
@colynb they use `--stage` in the docs, so I think it makes sense 😄

**Comment by Ryanb58** [comment]
This would be a nice feature to have. Currently, my `sls deploy` command looks like this:
```
sls deploy -s beta --env beta 
```

Which as everyone can see is repetitive. 

I do agree with @colynb that we need to ensure this PR is backward compatibility.

**Comment by atomicleopard** [comment]
Any progress on this - it would be very helpful

**Comment by neverendingqs** [comment]
Looks like this was resolved by https://github.com/neverendingqs/serverless-dotenv-plugin/pull/51. Please let me know if I have misunderstood. Thanks.

**Pull request closed without merging**
